version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongo_data/mongodb:/data/db
    ports:
      -  127.0.0.1:27017:27017
      -  192.168.6.55:27017:27017

  redis:
    image: redis:alpine
    restart: always
    logging:
      driver: none

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'

  typecho:
    build:
      context: docker/typecho/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./www/www.tougetu.com:/var/www/html

  piwigo:
    build:
      context: docker/piwigo/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./www/gakki.photos:/var/www/html

  ipv4:
    image: bennythink/ipv4.fail
    restart: unless-stopped

  yyets-web:
    image: bennythink/yyetsbot
    restart: always
    environment:
      - mongo=mongo
    working_dir: /YYeTsBot/web/
    volumes:
      - ./data:/YYeTsBot/web/data/
    command: [ "python3","server.py","-h=0.0.0.0" ]

  nginx:
    restart: always
    image: nginx:alpine
    volumes:
      - ./conf:/etc/nginx/conf.d
      - /home/photos:/usr/share/nginx/html/photos
      - ./certs/:/etc/nginx/certs/
    ports:
      - 80:80
      - 443:443