version: '3.1'

services:
  mongo:
    image: mongo:6
    restart: always
    volumes:
      - ./mongo_data/mongodb:/data/db
    ports:
      - "127.0.0.1:27017:27017"
      - "192.168.6.2:27017:27017"
      - "172.17.0.1:27017:27017"
    command: --quiet
    logging:
      driver: none

  redis:
    image: redis:7-alpine
    restart: always
    logging:
      driver: none
    ports:
      - "192.168.6.2:6379:6379"

  mysql:
    image: ubuntu/mysql:8.0-22.04_beta
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    logging:
      driver: none
    ports:
      - "192.168.6.2:3306:3306"
    command: "--skip-log-bin"

  piwigo:
    image: bennythink/php:8.2
    restart: always
    depends_on:
      - nginx
      - mysql
    volumes:
      - ./www/gakki.photos:/var/www/html

  ipv4:
    image: bennythink/ipv4.fail
    restart: unless-stopped
    depends_on:
      - nginx

  yyets-web:
    image: bennythink/yyetsbot
    restart: always
    environment:
      - mongo=mongo
      - redis=redis
    env_file:
      - conf/yyets.env
    depends_on:
      - mongo
      - redis
      - nginx
    working_dir: /YYeTsBot/yyetsweb/
    command: [ "python3","server.py","-h=0.0.0.0" ]

  nginx:
    restart: always
    image: nginx:stable-alpine
    volumes:
      - ./conf:/etc/nginx/conf.d
      - /home/photos:/usr/share/nginx/html/photos
      - ./certs/:/etc/nginx/certs/
      - ./logs:/var/log/nginx/
    ports:
      - "80:80"
      - "443:443"
    environment:
      TZ: Europe/Stockholm

  influxdb:
    restart: on-failure
    image: influxdb:1.8.10
    volumes:
      - ./influxdb:/var/lib/influxdb
    ports:
      - "192.168.6.2:8086:8086"

  grafana:
    restart: on-failure
    image: grafana/grafana:9.1.2
    volumes:
      - ./grafana:/var/lib/grafana
#      - ./conf/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - "172.17.0.1:3000:3000"
    environment:
      GF_INSTALL_PLUGINS: grafana-piechart-panel,simpod-json-datasource
