version: '3.1'

services:
  db:
    image: mysql/mysql-server:8.0
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'

  piwigo:
    build:
      context: docker/piwigo/
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - nginx
      - db
    volumes:
      - ./www/gakki.photos:/var/www/html

  nginx:
    restart: always
    image: nginx:alpine
    volumes:
      - ./conf:/etc/nginx/conf.d
      - /home/photos:/usr/share/nginx/html/photos
      - ./certs/:/etc/nginx/certs/
    ports:
      - 80:80
      - 443:443
