version: '3.1'

services:
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'

  typecho:
    build:
      context: docker/typecho/
      dockerfile: Dockerfile
    restart: always
    volumes:
    - ./www/www.tougetu.com:/var/www/html

  piwigo:
    build:
      context: docker/piwigo/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./www/gakki.photos:/var/www/html

  ipv4:
    image: bennythink/ipv4.fail
    restart: unless-stopped

  nginx:
    restart: always
    image: nginx:alpine
    volumes:
      - ./conf:/etc/nginx/conf.d
      - /home/photos:/usr/share/nginx/html/photos
    ports:
      - 80:80
      - 443:443