version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'

  typecho:
    build:
      context: docker/typecho/
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
    - ./www/www.tougetu.com:/var/www/html

  piwigo:
    build:
      context: docker/piwigo/
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./www/gakki.photos:/var/www/html

  ipv4:
    image: bennythink/ipv4.fail
    restart: on-failure

  nginx:
    image: nginx:alpine
    volumes:
      - ./conf:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443