version: '3.1'

services:
  mysql:
    image: ubuntu/mysql:8.0-22.04_beta
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    logging:
      driver: none
    ports:
      - "127.0.0.1:3306:3306"
    command: "--skip-log-bin"

  piwigo:
    image: bennythink/php:8.2
    restart: unless-stopped
    depends_on:
      - mysql
    volumes:
      - ./www/gakki.photos:/var/www/html
    ports:
      - "127.0.0.1:10000:80"

  ipv4:
    image: bennythink/ipv4.fail
    restart: unless-stopped
    ports:
      - "127.0.0.1:10001:6789"

  bot:
    restart: unless-stopped
    image: nginx:stable-alpine
    volumes:
      - ./conf:/etc/nginx/conf.d
      - /home/photos:/usr/share/nginx/html/photos
    ports:
      - "127.0.0.1:10002:80"
    environment:
      TZ: Europe/Stockholm
